name: llm-26-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - networkx
  - psutil
  - spacy
  - tiktoken
  - datasets
  - transformers
  - huggingface_hub
  - modelscope
  - regex
  - addict
  - spacy-pkuseg
  - spacy-model-en_core_web_sm
  - spacy-model-zh_core_web_sm
  - nbconvert

  # Force GPU PyTorch from pytorch channel
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch-cuda=12.1

  # Local LLM
  - conda-forge::ollama
  - ollama-python
  - requests