name: llm-26-cpu
channels:
  - defaults
dependencies:
  - python=3.12
  - jupyterlab
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
  - numpy
  - pandas
  - tqdm
  - conda-forge::ollama
  - ollama-python
  - spacy
  - conda-forge::tiktoken
  - pytorch
  - torchaudio
  - torchvision
  - datasets
  - transformers
  - huggingface_hub
  - conda-forge::modelscope
  - regex
  - addict
  - requests
  - matplotlib
  - networkx
  - psutil
  - spacy-pkuseg
  - spacy-model-en_core_web_sm
  - spacy-model-zh_core_web_sm
  - nbconvert
